version: "3.7"

services:
  web:
    image: "registry.thinklabs.com.vn:5000/traceabilityweb:latest"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.environment==development]
      restart_policy:
        condition: any
    environment:
      PORT: 80
      NODE_ENV: "production"
      SERVICE_80_NAME: "SafeDriveweb"
      SERVICE_NAME: "SafeDriveweb"
      SERVICE_TAGS: "SafeDriveweb"
    ports:
      - target: 80
        published: 8075
        mode: hosts
